version: "3.8"

services:
  devcontainer:
    build:
      context: ./.devcontainer
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/workspace
      - ~/.ssh:/home/vscode/.ssh:ro
    ports:
      - 0.0.0.0:8010:8010